// State hub pages. These carry the state-level layer that a single city page cannot:
// how policing is organised across the state, what the state lets you report online,
// which helplines the state actually publishes, and any state rule on accommodation.
// They also name the districts and towns that are too small for a page of their own.
export interface StateData {
  slug: string;
  state: string;
  seoTitle: string;
  heroTitle: string;
  heroSubtitle: string;
  metaDescription: string;
  intro: string;
  /** Who polices what across the state, and where the boundaries catch people out. */
  policing: { heading: string; body: string[] };
  /** What can and cannot be filed online here, and the helplines the state publishes. */
  reporting: { heading: string; body: string[] };
  /** Any state rule on hotels, lodges, paying guest accommodation or hostels. */
  accommodation?: { heading: string; body: string[] };
  /** Districts with their principal towns. This is where the long tail of place names lives. */
  districts: { district: string; towns: string[] }[];
  /** Slugs of city pages in this state, linked as the deeper reads. */
  cityPages: string[];
  faqs: { q: string; a: string }[];
}

export const states: StateData[] = [
  {
    slug: "tamil-nadu",
    state: "Tamil Nadu",
    seoTitle: "Bug Sweeping Services in Tamil Nadu | TSCM Sweeps",
    heroTitle: "Bug Sweeping Services in Tamil Nadu",
    heroSubtitle:
      "TSCM bug sweeps across Tamil Nadu, with the state level detail that decides who takes your complaint and what you can actually file.",
    metaDescription:
      "Bug sweeping services across Tamil Nadu: TSCM sweeps district by district, with the state's policing structure, reporting rules and hostel law explained.",
    intro:
      "Tamil Nadu publishes more about its own policing than most states do, which works in your favour on the day something is found: the structure, the station numbers and the helpline list are all set out in the state's annual policy note, so it is usually possible to establish who takes a complaint before you make it. The sweep itself does not change from place to place. It combines radio-frequency analysis for anything transmitting, a non-linear junction detector that picks up electronics left switched off, optical and thermal checks, and a physical inspection of the places a device can be concealed. What this page adds is the layer around that work.",
    policing: {
      heading: "Nine commissionerates, and in eight of them the city and the district are different forces",
      body: [
        "Tamil Nadu is policed as nine commissionerates alongside thirty seven police districts, with two railway police districts on top and two hundred and seventy seven sub-divisions beneath. The commissionerates are Greater Chennai, Tambaram, Avadi, Tiruchirappalli, Coimbatore, Salem, Madurai, Tirunelveli and Tiruppur. If your address is not inside one of those nine, it sits in a police district under a superintendent, and the chain of command above your station officer is a different one.",
        "The detail that costs people a day is this: in eight of those nine cities, the city force and the surrounding district are separate, each with its own head. Coimbatore city and Coimbatore district are not the same force. Only Chennai is policed as a single unit, and even there the metropolitan area splits three ways, because Tambaram and Avadi were carved out of the old Greater Chennai area and now stand on their own. Tiruppur is its own commissionerate rather than part of Coimbatore, which surprises people who think of the two cities as one industrial belt. Railway premises anywhere in the state belong to a railway police district rather than the local force, so an incident on a platform is not a matter for the city police outside.",
        "Cyber coverage is unusually deep. The policy note lists fifty four cyber crime police stations, made up of one for each police district, one for each commissionerate, three specialised stations attached to the wings handling crimes against women and children, economic offences and the crime branch, and four zonal stations inside Chennai city. The State Cyber Crime Investigation Centre sits at the Cyber Crime Wing headquarters in Chennai and takes cases where jurisdiction cannot be established, which is often exactly the position you are in when a recording surfaces online and nobody can say where it was made.",
      ],
    },
    reporting: {
      heading: "An online complaint here is not an FIR, and the women's helpline is 1091",
      body: [
        "Start with the number, because this one changed recently. Tamil Nadu notified 1091 as the line for the Singappen Special Task Force, launched across the state on 9 June 2026 and integrated with the 112 emergency system, with seventy field units operating statewide. It is the same 1091 that the state's helpline list has long carried as the women's helpline, now with that force behind it. Any guidance written before the middle of 2026 will not mention the change, and anything telling you 1091 is a Chennai arrangement is wrong.",
        "The number that does not apply here is 181. Several states use it as their women's helpline. In Tamil Nadu it does not appear on the police emergency list at all, because it belongs to social welfare rather than the police. The list the state actually publishes runs 100 for the control room, 112 for emergencies, 1091 for women, 1098 for children, 1930 for cyber financial fraud, 103 for traffic violations, 108 for ambulance, 1093 for coastal security, 1512 for the railway police, 10581 for prohibition and drug matters, 1800 180 5522 for anti-ragging and 94999 57575 for the senior citizens line.",
        "Then the part that catches most people. You can register a complaint online through the state citizen services portal, check its status and view FIR details, but the state's own service list treats a registered online complaint, a community service register entry and an FIR as three separate things. A community service register entry is what a non-cognizable matter produces, and it is not an FIR. Voyeurism under the Bharatiya Nyaya Sanhita is cognizable, so a covert recording complaint is not something you finish from a laptop: it is made at the police station, and since February 2026 it is registered on the upgraded records system now used in every station in the state.",
      ],
    },
    accommodation: {
      heading: "There is a real camera duty here, and a hostel licence that says nothing about cameras",
      body: [
        "Two separate things get run together constantly, and the difference matters. The first is a genuine statutory duty. Since January 2025, an amendment to the state's harassment law has required whoever is in charge of an educational institution, hostel, place of worship, cinema, hotel, restaurant, hospital, mall or any other precinct to take steps including installing cameras to prevent harassment of a woman within that precinct, and, once a complaint is made, to inform the police within twenty four hours. The fine for breach was raised to fifty thousand rupees. That catch-all phrase, any other precinct, is broad enough to reach lodges, paying guest accommodation and offices.",
        "What the duty does not do is set a standard. It prescribes no retention period, no resolution, no placement and no coverage, and no rules have been made under it, so there is no camera specification anywhere in Tamil Nadu law. It is a duty to take steps, enforced through a fine, not a technical standard you can hold a hotel to. Its practical value to you is the second limb rather than the first: if you report a device and the premises stall, that twenty four hour reporting duty is a lever.",
        "The second thing is hostel licensing, and it is narrower than people assume. The Tamil Nadu Hostels and Homes for Women and Children (Regulation) Act 2014 covers buildings providing accommodation for women or children. It is not a hotels law. The licence comes from the district Collector, not the police, and an amendment in May 2025 moved applications online and extended the licence from three years to ten, at a fee of ten thousand rupees. Cameras survive in that regime only as a self-declared line on a security annexure, asking how many there are and where, alongside a visitor logbook and an emergency exit plan. The licence conditions themselves do not mention cameras at all. So a licensed hostel may have none, and one that does has chosen their positions itself. Neither tells you anything about a device hidden inside a room.",
        "We found no advisory from Tamil Nadu Police specifically about hidden or spy cameras in hotels, hostels, trial rooms or washrooms. Where a state has issued one we say so. Here there is none to point you at.",
      ],
    },
    cityPages: ["chennai", "coimbatore"],
    districts: [
      { district: "Chennai", towns: ["Chennai"] },
      { district: "Chengalpattu", towns: ["Chengalpattu", "Tambaram", "Maraimalai Nagar", "Mamallapuram", "Sriperumbudur"] },
      { district: "Tiruvallur", towns: ["Tiruvallur", "Avadi", "Ponneri", "Gummidipoondi", "Tiruttani", "Poonamallee"] },
      { district: "Kancheepuram", towns: ["Kancheepuram", "Uthiramerur", "Walajabad"] },
      { district: "Coimbatore", towns: ["Coimbatore", "Mettupalayam", "Pollachi", "Valparai", "Annur"] },
      { district: "Tiruppur", towns: ["Tiruppur", "Udumalaipettai", "Palladam", "Avinashi", "Dharapuram", "Kangeyam"] },
      { district: "Erode", towns: ["Erode", "Gobichettipalayam", "Bhavani", "Sathyamangalam", "Perundurai", "Chennimalai"] },
      { district: "Salem", towns: ["Salem", "Mettur", "Attur", "Sankari", "Omalur", "Edappadi"] },
      { district: "Namakkal", towns: ["Namakkal", "Rasipuram", "Tiruchengode", "Kumarapalayam", "Paramathi Velur"] },
      { district: "Dharmapuri", towns: ["Dharmapuri", "Harur", "Palacode", "Pennagaram"] },
      { district: "Krishnagiri", towns: ["Krishnagiri", "Hosur", "Denkanikottai", "Bargur"] },
      { district: "Tirupathur", towns: ["Tirupathur", "Vaniyambadi", "Ambur", "Jolarpettai", "Natrampalli"] },
      { district: "Vellore", towns: ["Vellore", "Katpadi", "Gudiyatham", "Pernambut", "Anaicut"] },
      { district: "Ranipet", towns: ["Ranipet", "Arakkonam", "Walajapet", "Arcot", "Sholingur"] },
      { district: "Tiruvannamalai", towns: ["Tiruvannamalai", "Arani", "Cheyyar", "Polur", "Chengam", "Vandavasi"] },
      { district: "Viluppuram", towns: ["Viluppuram", "Tindivanam", "Gingee", "Vikravandi"] },
      { district: "Kallakurichi", towns: ["Kallakurichi", "Chinnasalem", "Ulundurpet", "Sankarapuram"] },
      { district: "Cuddalore", towns: ["Cuddalore", "Chidambaram", "Neyveli", "Virudhachalam", "Panruti"] },
      { district: "Mayiladuthurai", towns: ["Mayiladuthurai", "Sirkali", "Tharangambadi", "Kuthalam"] },
      { district: "Nagapattinam", towns: ["Nagapattinam", "Velankanni", "Kilvelur", "Vedaranyam"] },
      { district: "Thiruvarur", towns: ["Thiruvarur", "Mannargudi", "Thiruthuraipoondi", "Needamangalam", "Kodavasal"] },
      { district: "Thanjavur", towns: ["Thanjavur", "Kumbakonam", "Pattukkottai", "Papanasam", "Orathanadu"] },
      { district: "Tiruchirappalli", towns: ["Tiruchirappalli", "Srirangam", "Manapparai", "Musiri", "Lalgudi", "Thuraiyur"] },
      { district: "Perambalur", towns: ["Perambalur", "Kunnam", "Veppanthattai"] },
      { district: "Ariyalur", towns: ["Ariyalur", "Jayankondam", "Sendurai"] },
      { district: "Karur", towns: ["Karur", "Kulithalai", "Krishnarayapuram", "Aravakurichi"] },
      { district: "Pudukkottai", towns: ["Pudukkottai", "Aranthangi", "Alangudi", "Ponnamaravathi", "Iluppur"] },
      { district: "Sivaganga", towns: ["Sivaganga", "Karaikudi", "Devakottai", "Manamadurai", "Ilayangudi"] },
      { district: "Madurai", towns: ["Madurai", "Usilampatti", "Melur", "Thirumangalam", "Sholavandan"] },
      { district: "Theni", towns: ["Theni", "Bodinayakanur", "Cumbum", "Periyakulam", "Andipatti"] },
      { district: "Dindigul", towns: ["Dindigul", "Palani", "Kodaikanal", "Oddanchatram", "Batlagundu"] },
      { district: "Ramanathapuram", towns: ["Ramanathapuram", "Rameswaram", "Paramakudi", "Kamuthi", "Mandapam"] },
      { district: "Virudhunagar", towns: ["Virudhunagar", "Sivakasi", "Rajapalayam", "Srivilliputhur", "Aruppukkottai", "Sattur"] },
      { district: "Tenkasi", towns: ["Tenkasi", "Sankarankoil", "Courtallam", "Kadayanallur", "Shenkottai"] },
      { district: "Tirunelveli", towns: ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Nanguneri", "Cheranmadevi"] },
      { district: "Thoothukudi", towns: ["Thoothukudi", "Kovilpatti", "Tiruchendur", "Srivaikuntam", "Sathankulam"] },
      { district: "Kanniyakumari", towns: ["Nagercoil", "Marthandam", "Colachel", "Kuzhithurai", "Kanniyakumari"] },
      { district: "The Nilgiris", towns: ["Udhagamandalam", "Coonoor", "Kotagiri", "Gudalur", "Kethi"] },
    ],
    faqs: [
      {
        q: "Which police force covers my address in Tamil Nadu?",
        a: "Nine areas are commissionerates: Greater Chennai, Tambaram, Avadi, Tiruchirappalli, Coimbatore, Salem, Madurai, Tirunelveli and Tiruppur. Everywhere else is one of thirty seven police districts under a superintendent. In eight of the nine cities the city force and the surrounding district are separate, and the Chennai metropolitan area splits three ways, so confirm the station before you report anything.",
      },
      {
        q: "Is 181 the women's helpline in Tamil Nadu?",
        a: "No. It does not appear on the Tamil Nadu Police emergency helpline list, because in this state it sits with social welfare rather than the police. The police line is 1091, which is both the published women's helpline and, since 9 June 2026, the number for the Singappen Special Task Force, integrated with 112.",
      },
      {
        q: "Can I report a hidden camera online in Tamil Nadu?",
        a: "You can lodge a complaint online, but that is not an FIR. The state's own service list separates a registered online complaint, a community service register entry and an FIR, and a community service register entry is what a non-cognizable matter produces. Voyeurism is cognizable, so expect to attend the police station and ask for an FIR.",
      },
      {
        q: "Does a hotel or hostel in Tamil Nadu have to have cameras?",
        a: "There is a duty, but no standard. Since January 2025 the person in charge of a hotel, hostel, restaurant, cinema, mall, hospital or any other precinct must take steps including installing cameras to prevent harassment of a woman, and must inform the police within twenty four hours of a complaint. No retention period, resolution or placement is prescribed. Separately, a women's or children's hostel needs a Collector's licence, now valid ten years, whose conditions do not mention cameras at all.",
      },
      {
        q: "Do you cover towns outside the main cities?",
        a: "Yes. Sweeps are arranged across the state, including the district towns named in the table on this page. Chennai and Coimbatore have pages of their own because we have verified local detail worth publishing for them; that is not a limit on where we work.",
      },
    ],
  },
  {
    slug: "gujarat",
    state: "Gujarat",
    seoTitle: "Bug Sweeping Services in Gujarat | TSCM Sweeps",
    heroTitle: "Bug Sweeping Services in Gujarat",
    heroSubtitle:
      "TSCM bug sweeps across Gujarat, from the four commissionerate cities to the district towns and industrial estates.",
    metaDescription:
      "Bug sweeping services across Gujarat: TSCM sweeps district by district, with the state's policing structure, e-FIR limits and hotel reporting rules explained.",
    intro:
      "Gujarat concentrates a great deal of value in a small number of rooms: diamond units, textile buying offices, chemical and engineering plants, and the family businesses that sit behind them. The sweep we run is the same everywhere, using radio-frequency analysis for anything transmitting, a non-linear junction detector for electronics that are switched off, optical and thermal checks and a physical inspection. What changes across the state is who polices your address, what the state lets you file online, and how much of your own movement is already on record.",
    policing: {
      heading: "Only four cities have a Police Commissioner, and each has a separate rural force",
      body: [
        "Gujarat has four police commissionerates and no more: Ahmedabad City, Surat City, Vadodara City and Rajkot City. Everywhere else in the state is a district under a superintendent, grouped into ranges under an inspector general or deputy inspector general. Two claims circulate widely and both are wrong. The first adds Jamnagar, Bhavnagar and Junagadh to the list; those are district superintendencies, and the range offices there are range offices, not commissionerates. The second adds Gandhinagar; a commissionerate there has been proposed for years and has not been approved, so it does not exist. The eight city list people quote is the rollout list for a public safety camera law, which is a different thing entirely.",
        "In each of the four commissionerate cities there is also a separate rural force with its own superintendent. Ahmedabad Rural, Surat Rural, Vadodara Rural and Rajkot Rural are not the city force. This is the boundary that costs time: an industrial estate or a plant on the edge of a city very often sits on the rural side, and a complaint made to the wrong office starts the day badly. If your address is anywhere near a city limit, establish which force covers it before you need to.",
        "The state's district map itself changed recently. Gujarat has thirty four districts as of 2 October 2025, when Vav-Tharad was carved out of Banaskantha and became the thirty fourth. Some government pages have not caught up and still show thirty three. Vav-Tharad also functions as a police district in its own right.",
        "On cyber matters the state runs a cyber crime cell under the CID at Gandhinagar, with cyber crime police stations at commissionerate level, at range level and in a growing number of districts. Sources disagree on the current total, so we do not publish a number; what matters is that a cyber station exists at or above your district and that 1930 and the national portal will route a complaint if you are unsure.",
      ],
    },
    reporting: {
      heading: "The e-FIR covers almost nothing, and an online complaint is a separate thing again",
      body: [
        "Gujarat's e-FIR is narrower than its name suggests. It covers vehicle and mobile phone theft only, and only where the accused is unidentified and no force was used. It is also not an FIR at the moment you submit it: a senior officer assigns a preliminary check within twenty four hours, the investigating officer verifies the complainant within around forty eight hours, and only then is it converted into an FIR. A covert recording complaint is outside that route completely, so it is made in person at the police station.",
        "The state portal also runs e-complaint and e-FIR as two different services, and the volumes make the point better than any explanation: e-complaints filed run into the hundreds of thousands while e-FIRs are a small fraction of that. Filing something online in Gujarat usually produces a complaint, not a registered FIR, and only the second of those starts an investigation.",
        "On helplines, Gujarat Police's own published list gives 100 and 112 for police, 181 as the Abhayam women's helpline, 1930 for cyber complaints, 1098 for children, 108 for ambulance and 101 for fire. Two caveats are worth carrying. The 181 Abhayam line is run by the women and child development department rather than the police, and that department says itself that its rescue team is not a substitute for the police. And although 181 is the number on the police list, 1091 still appears on some district collectorate pages, so the two coexist and it is worth checking what your own district publishes. The traffic number still printed on some official pages was retired as a complaint line in August 2026 when traffic complaints were folded into 112.",
      ],
    },
    accommodation: {
      heading: "Your hotel has probably already sent your identity to the police",
      body: [
        "Gujarat runs a hotel reporting system that most guests never hear about. Under a police order made using the Gujarat Police Act, hotels keep a networked terminal at reception and upload each guest's name, address, mobile number, identity document and period of stay, in real time rather than in a book checked later. It began with the Ahmedabad crime branch and has spread well beyond it, and enforcement is real: a hotel manager in Ahmedabad was booked in February 2026 for failing to upload guest details. Paying guest accommodation has been pulled into the same registration push.",
        "That is worth knowing for a practical reason. If you find a device in a hotel room and need to establish who else had access to it, the occupancy record you are asking about is not an informal register that may or may not have been kept. It is a record the hotel was legally required to file with the police as it went along.",
        "What Gujarat does not have is a camera mandate you can rely on inside accommodation. The state's public safety law requires cameras covering entry and exit points and parking, with thirty days of storage, but only at premises the government has notified by footfall, and the categories reported in that notification are educational institutions, sports complexes, religious places and industrial areas rather than hotels. We could not verify the notified list directly, so we do not claim it covers your hotel. Separately there is no state statute on paying guest accommodation or hostels at all; regulation is municipal, and the High Court held in 2025 that running premises as a homestay or paying guest hostel without permission from the local authority is not allowed. Some districts add their own requirements by magistrate's order, typically a visitor register and cameras at entrances and parking with thirty day retention, but those are district orders that lapse and renew rather than state law.",
        "We found no advisory from Gujarat Police specifically about hidden or spy cameras. Its own public awareness campaigns cover online fraud, grooming, sextortion and deepfakes, and do not touch covert recording devices.",
      ],
    },
    cityPages: ["ahmedabad", "surat"],
    districts: [
      { district: "Ahmedabad", towns: ["Ahmedabad", "Dholka", "Sanand", "Bavla", "Viramgam", "Dhandhuka"] },
      { district: "Gandhinagar", towns: ["Gandhinagar", "Kalol", "Dehgam", "Mansa", "Pethapur", "Chhatral"] },
      { district: "Surat", towns: ["Surat", "Bardoli", "Mandvi", "Olpad", "Kamrej", "Palsana"] },
      { district: "Vadodara", towns: ["Vadodara", "Padra", "Dabhoi", "Savli", "Karjan", "Waghodia"] },
      { district: "Rajkot", towns: ["Rajkot", "Gondal", "Jetpur", "Dhoraji", "Upleta", "Jasdan", "Paddhari"] },
      { district: "Bhavnagar", towns: ["Bhavnagar", "Palitana", "Mahuva", "Sihor", "Gariadhar", "Talaja"] },
      { district: "Jamnagar", towns: ["Jamnagar", "Dhrol", "Kalavad", "Jamjodhpur", "Sikka", "Bedi"] },
      { district: "Junagadh", towns: ["Junagadh", "Keshod", "Mangrol", "Manavadar", "Visavadar", "Vanthali"] },
      { district: "Kutch", towns: ["Bhuj", "Gandhidham", "Anjar", "Mandvi", "Mundra", "Bhachau", "Rapar", "Kandla"] },
      { district: "Bharuch", towns: ["Bharuch", "Ankleshwar", "Jambusar", "Dahej", "Amod", "Valia"] },
      { district: "Navsari", towns: ["Navsari", "Bilimora", "Gandevi", "Chikhli", "Vansda"] },
      { district: "Valsad", towns: ["Valsad", "Vapi", "Pardi", "Umbergaon", "Dharampur", "Atul"] },
      { district: "Tapi", towns: ["Vyara", "Songadh", "Ukai", "Valod", "Nizar"] },
      { district: "Dang", towns: ["Ahwa", "Waghai", "Saputara", "Subir"] },
      { district: "Anand", towns: ["Anand", "Vallabh Vidyanagar", "Khambhat", "Petlad", "Borsad", "Umreth"] },
      { district: "Kheda", towns: ["Nadiad", "Kapadvanj", "Mahudha", "Thasra", "Kathlal", "Dakor"] },
      { district: "Panchmahal", towns: ["Godhra", "Halol", "Shehera", "Morwa Hadaf"] },
      { district: "Mahisagar", towns: ["Lunawada", "Balasinor", "Santrampur", "Virpur", "Kadana"] },
      { district: "Dahod", towns: ["Dahod", "Jhalod", "Limkheda", "Devgadh Baria", "Sanjeli"] },
      { district: "Chhota Udepur", towns: ["Chhota Udaipur", "Bodeli", "Kavant", "Sankheda"] },
      { district: "Narmada", towns: ["Rajpipla", "Dediapada", "Sagbara", "Kevadiya", "Garudeshwar"] },
      { district: "Mehsana", towns: ["Mehsana", "Visnagar", "Kadi", "Unjha", "Vijapur", "Vadnagar", "Becharaji"] },
      { district: "Patan", towns: ["Patan", "Sidhpur", "Chanasma", "Harij", "Radhanpur", "Santalpur"] },
      { district: "Banaskantha", towns: ["Palanpur", "Deesa", "Danta", "Amirgadh", "Vadgam"] },
      { district: "Vav-Tharad", towns: ["Tharad", "Vav", "Bhabhar", "Deodar", "Lakhani", "Suigam"] },
      { district: "Sabarkantha", towns: ["Himmatnagar", "Idar", "Khedbrahma", "Prantij", "Talod", "Vadali"] },
      { district: "Aravalli", towns: ["Modasa", "Bayad", "Malpur", "Meghraj", "Dhansura"] },
      { district: "Surendranagar", towns: ["Surendranagar", "Wadhwan", "Limbdi", "Dhrangadhra", "Chotila", "Thangadh"] },
      { district: "Morbi", towns: ["Morbi", "Wankaner", "Halvad", "Maliya", "Tankara"] },
      { district: "Botad", towns: ["Botad", "Gadhada", "Barwala", "Ranpur"] },
      { district: "Amreli", towns: ["Amreli", "Savarkundla", "Rajula", "Babra", "Lathi", "Damnagar"] },
      { district: "Gir Somnath", towns: ["Veraval", "Somnath", "Kodinar", "Una", "Talala", "Sutrapada"] },
      { district: "Porbandar", towns: ["Porbandar", "Ranavav", "Kutiyana"] },
      { district: "Devbhoomi Dwarka", towns: ["Khambhalia", "Dwarka", "Okha", "Bhanvad", "Salaya", "Mithapur"] },
    ],
    faqs: [
      {
        q: "Which cities in Gujarat have a Police Commissioner?",
        a: "Four: Ahmedabad, Surat, Vadodara and Rajkot. Everywhere else, including Jamnagar, Bhavnagar, Junagadh and Gandhinagar, is a district under a superintendent. Each of the four cities also has a separate rural force with its own superintendent, so an address near a city limit may not be the city police at all.",
      },
      {
        q: "Can I file an e-FIR in Gujarat for a hidden camera?",
        a: "No. The e-FIR covers vehicle and mobile phone theft only, where the accused is unidentified and no force was used, and even then it becomes an FIR only after an officer verifies the complainant, reported as within forty eight hours. A covert recording complaint is made in person at the police station.",
      },
      {
        q: "Which women's helpline does Gujarat publish?",
        a: "Gujarat Police's own list gives 181, the Abhayam line, which is run by the women and child development department rather than the police. The 1091 number still appears on some district collectorate pages, so both circulate and it is worth checking what your district publishes. Use 112 for an emergency and 1930 for cyber crime.",
      },
      {
        q: "Does my hotel in Gujarat have to report who stays there?",
        a: "Yes. Hotels upload guest name, address, mobile number, identity document and period of stay to the police in real time from a terminal at reception, and enforcement is active: a hotel manager in Ahmedabad was booked in February 2026 for not doing it. If you need to establish who had access to a room, that record exists.",
      },
      {
        q: "How many districts does Gujarat have?",
        a: "Thirty four, since 2 October 2025, when Vav-Tharad was created out of Banaskantha. Some government pages still show thirty three because they have not been updated. Vav-Tharad also operates as a police district in its own right.",
      },
    ],
  },
  {
    slug: "bihar",
    state: "Bihar",
    seoTitle: "Bug Sweeping Services in Bihar | TSCM Sweeps",
    heroTitle: "Bug Sweeping Services in Bihar",
    heroSubtitle:
      "TSCM bug sweeps across Bihar, with the state's SP-led policing structure and its reporting limits set out plainly.",
    metaDescription:
      "Bug sweeping services across Bihar: TSCM sweeps district by district, with the state's policing structure, the absence of an e-FIR and the hostel circular explained.",
    intro:
      "Bihar is policed differently from most of the states around it, and the difference is not cosmetic: it changes who you escalate to and what you can do without walking into a police station. The sweep itself is unchanged wherever we work, combining radio-frequency analysis, a non-linear junction detector that finds electronics left switched off, optical and thermal checks and a physical inspection. What this page sets out is the part that decides what happens next.",
    policing: {
      heading: "There is no police commissionerate anywhere in Bihar",
      body: [
        "Every district in Bihar, Patna included, is headed by a superintendent or senior superintendent of police working under the district magistrate's general direction and control. This is not an accident of appointments: the Bihar Police Act 2007 contains no definition of a Commissioner of Police, no commissionerate chapter and no power to declare one. It says the opposite, vesting the police administration of a district in the superintendent under the district magistrate. A Patna commissionerate has been talked about but nothing has been approved.",
        "The practical consequence is worth understanding. In a commissionerate state the police chain is self-contained and the district magistrate sits outside it. In Bihar the district magistrate is inside the chain, which makes that office a real escalation route in a way it is not in Maharashtra or Tamil Nadu. If a complaint stalls at the station and then at the superintendent, the district magistrate is not a detour.",
        "The state has thirty eight districts, grouped into twelve police ranges. The last new district, Arwal, was created in August 2001 out of Jehanabad, and none has been created since. For policing purposes the count is different from the revenue count in a way that matters when you are working out where to report: Bagaha and Naugachhia are police districts of their own on top of the thirty eight, and four railway police districts sit alongside them at Patna, Muzaffarpur, Katihar and Jamalpur.",
        "Cyber coverage is better than the state's reputation suggests. There is a cyber police station in every police district, opened across the state in June 2023, and the state nodal body is the Economic Offences Unit at police headquarters in Patna rather than a separate cyber wing. If a complaint needs to go above your district, the Economic Offences Unit is where it goes.",
      ],
    },
    reporting: {
      heading: "Bihar has no e-FIR at all, whatever the website suggests",
      body: [
        "This is the single most important thing on this page. Bihar offers an e-complaint, not an e-FIR. The citizen services portal lists an e-complaint, a facility to view an FIR already registered, and an online request through the emergency response system. None of those registers an FIR. Some of the portal's own headings use the phrase file FIR online, which is loose wording with no service behind it, and you should expect someone to quote it at you. Plan on reaching a police station in person.",
        "That makes the documentation from a sweep more useful here than in states with a working online route, because what you carry into the station is what the complaint rests on. We record what was found and where it was found before anything is moved.",
        "On helplines, Bihar Police publishes 112 for police emergencies through the integrated response system, 1930 for cyber crime, 181 as the women's helpline, 1098 for children, 15545 for prohibition matters, which is specific to this state, and a dedicated CCTV help desk line. Two corrections are worth carrying, because both send people to the wrong place. The 1090 number that a great deal of syndicated advice gives to Bihar readers belongs to Uttar Pradesh and is not the line here. And Bihar Police's own site is internally inconsistent about the women's number, listing 181 on its emergency contacts page while a quick help widget on the same site shows 1091, so if one does not connect, try the other.",
      ],
    },
    accommodation: {
      heading: "The hostel circular is real, and the High Court has said it has no teeth",
      body: [
        "In February 2026 Bihar Police headquarters issued a circular covering girls' hostels and lodges. It is more wide-ranging than most summaries suggest: registration, police verification of staff, a female warden on duty at all times, cameras at entrances, corridors and dining areas with thirty days of retention, a visitor register with controls on male access, biometric attendance for residents and staff, lighting and sanitation standards, and display of emergency numbers including 112, with checks by the state's women's safety units.",
        "What it does not have is a penalty. In May 2026 the Patna High Court held that the circular provides no consequence for non-compliance, warned that it risked becoming a paper advisory, directed the state to amend it to add fines, penalties or closure, and ordered monthly compliance reports from district superintendents. So the requirements are real and worth quoting to a hostel, but nothing currently happens to an operator who ignores them. Ask, and treat the answer as information rather than assurance.",
        "For hotels and lodges the position is simpler and less comforting. No Bihar statute requires cameras in hotel or lodge rooms or common areas. The Bihar Municipal Act licenses lodging houses as a trade licence with no camera, register or identity duty attached, and the Bihar Police Act does not reach hotels at all. Where a camera requirement exists it comes from a district police standing order, and those cover entrances, reception, corridors and parking. None of them covers the inside of a guest room, which is the space you are actually asking about.",
        "As of September 2026 neither Bihar Police nor the state government has published any advisory specifically about hidden or spy cameras in hotel rooms, trial rooms, washrooms or hostels. That is a genuine gap rather than something we failed to find.",
      ],
    },
    cityPages: ["patna"],
    districts: [
      { district: "Patna", towns: ["Patna", "Danapur", "Barh", "Masaurhi", "Fatuha", "Bakhtiarpur", "Bihta", "Maner"] },
      { district: "Nalanda", towns: ["Biharsharif", "Rajgir", "Hilsa", "Islampur", "Silao"] },
      { district: "Bhojpur", towns: ["Arrah", "Jagdishpur", "Piro", "Koilwar", "Bihiya"] },
      { district: "Buxar", towns: ["Buxar", "Dumraon", "Chausa"] },
      { district: "Rohtas", towns: ["Sasaram", "Dehri", "Bikramganj", "Nokha", "Nasriganj"] },
      { district: "Kaimur", towns: ["Bhabua", "Mohania", "Ramgarh", "Chainpur"] },
      { district: "Gaya", towns: ["Gaya", "Bodh Gaya", "Sherghati", "Tikari", "Dobhi"] },
      { district: "Aurangabad", towns: ["Aurangabad", "Daudnagar", "Rafiganj", "Nabinagar", "Obra"] },
      { district: "Nawada", towns: ["Nawada", "Hisua", "Rajauli", "Warisaliganj"] },
      { district: "Jehanabad", towns: ["Jehanabad", "Makhdumpur"] },
      { district: "Arwal", towns: ["Arwal", "Kurtha"] },
      { district: "Saran", towns: ["Chapra", "Revelganj", "Marhaura", "Sonepur", "Dighwara"] },
      { district: "Siwan", towns: ["Siwan", "Maharajganj", "Mairwa", "Barharia"] },
      { district: "Gopalganj", towns: ["Gopalganj", "Mirganj", "Hathua", "Barauli"] },
      { district: "West Champaran", towns: ["Bettiah", "Bagaha", "Narkatiaganj", "Ramnagar", "Chanpatia"] },
      { district: "East Champaran", towns: ["Motihari", "Raxaul", "Areraj", "Chakia", "Dhaka", "Sugauli"] },
      { district: "Muzaffarpur", towns: ["Muzaffarpur", "Motipur", "Kanti", "Sahebganj", "Saraiya"] },
      { district: "Sitamarhi", towns: ["Sitamarhi", "Bairgania", "Belsand", "Pupri", "Janakpur Road"] },
      { district: "Sheohar", towns: ["Sheohar", "Piprahi"] },
      { district: "Vaishali", towns: ["Hajipur", "Lalganj", "Mahnar", "Mahua", "Bidupur"] },
      { district: "Darbhanga", towns: ["Darbhanga", "Benipur", "Jale", "Singhwara"] },
      { district: "Madhubani", towns: ["Madhubani", "Jhanjharpur", "Jainagar", "Benipatti", "Rajnagar"] },
      { district: "Samastipur", towns: ["Samastipur", "Dalsinghsarai", "Rosera", "Mohiuddinagar"] },
      { district: "Begusarai", towns: ["Begusarai", "Barauni", "Teghra", "Balia", "Bakhri"] },
      { district: "Khagaria", towns: ["Khagaria", "Gogri Jamalpur", "Parbatta"] },
      { district: "Munger", towns: ["Munger", "Jamalpur", "Kharagpur", "Tarapur"] },
      { district: "Lakhisarai", towns: ["Lakhisarai", "Barahiya", "Surajgarha"] },
      { district: "Sheikhpura", towns: ["Sheikhpura", "Barbigha"] },
      { district: "Jamui", towns: ["Jamui", "Jhajha", "Sikandra"] },
      { district: "Bhagalpur", towns: ["Bhagalpur", "Kahalgaon", "Sultanganj", "Naugachhia"] },
      { district: "Banka", towns: ["Banka", "Amarpur", "Katoria"] },
      { district: "Saharsa", towns: ["Saharsa", "Simri Bakhtiarpur", "Sonbarsa"] },
      { district: "Madhepura", towns: ["Madhepura", "Murliganj", "Singheshwar"] },
      { district: "Supaul", towns: ["Supaul", "Nirmali", "Birpur", "Triveniganj"] },
      { district: "Purnia", towns: ["Purnia", "Banmankhi", "Kasba", "Dhamdaha"] },
      { district: "Katihar", towns: ["Katihar", "Manihari", "Barsoi", "Kadwa"] },
      { district: "Araria", towns: ["Araria", "Forbesganj", "Jogbani"] },
      { district: "Kishanganj", towns: ["Kishanganj", "Thakurganj", "Bahadurganj"] },
    ],
    faqs: [
      {
        q: "Does Bihar have a police commissionerate?",
        a: "No, nowhere in the state. Every district including Patna is headed by a superintendent or senior superintendent under the district magistrate's general direction and control, and the Bihar Police Act 2007 does not even provide for a Commissioner of Police. One practical effect is that the district magistrate is a genuine escalation route here, which is not the case in commissionerate states.",
      },
      {
        q: "Can I file an FIR online in Bihar?",
        a: "No. Bihar offers an e-complaint, a facility to view an FIR already registered, and an online request through the emergency response system. None of them registers an FIR. Some headings on the state portal use the phrase file FIR online, but there is no such service behind it, so plan on attending the police station in person.",
      },
      {
        q: "Is 1090 the women's helpline in Bihar?",
        a: "No. That number belongs to Uttar Pradesh, and a lot of syndicated advice gives it to Bihar readers by mistake. Bihar Police publishes 181 on its emergency contacts page, although a quick help widget on the same site shows 1091, so try the other if one does not connect. Use 112 for an emergency, 1930 for cyber crime and 15545 for prohibition matters.",
      },
      {
        q: "Does the Bihar girls' hostel circular actually require CCTV?",
        a: "It requires cameras at entrances, corridors and dining areas with thirty days of retention, alongside registration, staff police verification, a female warden at all times, a visitor register and biometric attendance. But the Patna High Court held in May 2026 that the circular carries no penalty for non-compliance and directed the state to add one. Ask a hostel about it, and treat the answer as information rather than assurance.",
      },
      {
        q: "Are hotels in Bihar required to have cameras?",
        a: "No Bihar statute requires it. The municipal law licenses lodging houses as a trade licence with no camera or register duty, and the police Act does not reach hotels. Where a requirement exists it comes from a district police standing order and covers entrances, reception, corridors and parking, never the inside of a guest room.",
      },
    ],
  },
  {
    slug: "maharashtra",
    state: "Maharashtra",
    seoTitle: "Bug Sweeping Services in Maharashtra | TSCM Sweeps",
    heroTitle: "Bug Sweeping Services in Maharashtra",
    heroSubtitle:
      "TSCM bug sweeps across Maharashtra, with the city and rural policing split that decides who takes your complaint.",
    metaDescription:
      "Bug sweeping services across Maharashtra: TSCM sweeps district by district, with the state's commissionerates, helpline split and accommodation rules explained.",
    intro:
      "Maharashtra holds more of India's corporate decision-making than any other state, and with it the meetings that people most want to overhear. The sweep we run does not change from Mumbai to Nagpur: radio-frequency analysis for anything transmitting, a non-linear junction detector for electronics left switched off, optical and thermal checks, and a physical inspection of the places a device is actually concealed. What changes is the layer around it, and in this state the single most useful thing to know before something happens is which police force covers the address you are standing in.",
    policing: {
      heading: "Eleven commissionerate cities, and seven of them have a rural force as well",
      body: [
        "Maharashtra Police list eleven city commissionerates: Mumbai, Thane, Navi Mumbai, Mira-Bhayandar and Vasai-Virar, Pune, Pimpri-Chinchwad, Nagpur, Nashik, Chhatrapati Sambhajinagar, Amravati and Solapur. Two cautions come with that list. The department's own about page still says ten, so the count is inconsistent on its own website. And Kolhapur and Nanded are widely listed as commissionerates online but appear in the official unit list as district police, so treat those claims with suspicion.",
        "The part that decides where you go is the rural split. Seven of those eleven cities have a separate rural police district with its own superintendent: Thane, Pune, Nagpur, Nashik, Chhatrapati Sambhajinagar, Amravati and Solapur. If you are just outside one of those city limits, the rural force is a different office with a different head. The other four work differently. Mumbai City has no rural counterpart at all. Navi Mumbai and Pimpri-Chinchwad have no rural unit of their own, so the land around them belongs to Thane Rural and Pune Rural respectively. Mira-Bhayandar and Vasai-Virar was carved out of Thane Rural and Palghar, so those are its neighbours.",
        "That is the opposite of what a reader might assume from the map. Two addresses fifteen minutes apart on the same road can sit with different superintendents, and a factory or farmhouse on the edge of Pune or Nashik very often is not the city police at all.",
        "Three of the state's districts were renamed recently, which matters if you are working from an older list: Aurangabad is now Chhatrapati Sambhajinagar and Osmanabad is Dharashiv, both since September 2023, and Ahmednagar became Ahilyanagar in October 2024.",
        "On cyber matters the state runs Maharashtra Cyber from Mahape in Navi Mumbai rather than from Mumbai, with district cyber labs connected back to it. A government resolution dated 23 July 2026 formally designated that office the State Cyber Crime Coordination Centre. Sources disagree on how many cyber police stations exist and the authoritative listing could not be read, so we publish no number.",
      ],
    },
    reporting: {
      heading: "Which women's helpline you dial depends on where you are standing",
      body: [
        "Maharashtra Police publish the split on their own home page, and it catches out anyone working from national advice. The 103 women's safety line runs in the Mumbai, Thane and Navi Mumbai police units only. Everywhere else in Maharashtra the number is 1091. If you are in Pune, Nashik, Nagpur or anywhere outside those three units, 103 is not your number.",
        "There is a third number that is easy to confuse with both. The 181 line in Maharashtra is a women's helpline run by the women and child development department, not by the police. That is worth holding on to if you read advice written for another state, because 181 means something different in each: in Madhya Pradesh it is the Chief Minister's grievance line, and in Uttar Pradesh it is a women's welfare department service separate from the police.",
        "For cyber matters the state publishes 1930 alongside 14407. The 14407 line belongs to Maharashtra Cyber and runs statewide, so despite how often it is quoted as a city facility it is not specific to Nagpur or anywhere else. Emergencies go to 112, which the state runs as a single point of contact with location capture, panic button and SMS routes as well as voice.",
        "On what you can finish online, plan on attending a police station for anything cognizable. Voyeurism is cognizable. We were not able to re-read Mumbai Police's own statement of policy on this during the latest check because several of their pages were returning errors, so we describe the practical position rather than quoting a rule.",
      ],
    },
    accommodation: {
      heading: "No statewide camera duty, and one district order worth quoting",
      body: [
        "Maharashtra has no statewide rule requiring cameras in hotels, lodges or paying guest accommodation. The Maharashtra Police Act pulls lodging houses into a licensing power by defining them as places of public entertainment, but that power contains no camera clause and no guest register clause. There is also no statewide regulation of paying guest accommodation or private hostels at all: licensing is municipal and differs from one corporation to the next.",
        "The Mumbai order that circulates online is not current. It was a city prohibitory order made in January 2021 requiring cameras across twenty three categories of private establishment, and it ran for sixty days and expired in March 2021. Anyone presenting it as a standing Mumbai rule, or as a Maharashtra rule, is wrong on both counts.",
        "One district order is worth knowing about because of what it excludes. In Raigad, the Collector was reported in 2026 to have required accommodation providers to keep guest identity records for two years and to run cameras at entry and exit points, reception, corridors and parking with thirty days of retention, while expressly stating that cameras must not be inside rooms or bathrooms. That carve-out is the line to quote at any operator who suggests a camera in a room could be legitimate. It is a district order reported in the press rather than state law, so treat it as local and current only while it runs.",
        "Separately, and this one is central law rather than state law, the keeper of any hotel, guest house or hostel must report a foreign national's arrival and departure online. That duty applies across India, not only here.",
        "We found no advisory from Maharashtra Police specifically about hidden or spy cameras. There is none to point you at in this state.",
      ],
    },
    cityPages: ["mumbai", "pune", "nagpur"],
    districts: [
      { district: "Mumbai City", towns: ["Mumbai", "Fort", "Dadar"] },
      { district: "Mumbai Suburban", towns: ["Bandra", "Andheri", "Borivali"] },
      { district: "Thane", towns: ["Thane", "Kalyan-Dombivli", "Navi Mumbai", "Ulhasnagar", "Bhiwandi", "Mira-Bhayandar"] },
      { district: "Palghar", towns: ["Palghar", "Vasai-Virar", "Boisar", "Dahanu"] },
      { district: "Raigad", towns: ["Alibag", "Panvel", "Khopoli", "Mahad", "Pen"] },
      { district: "Ratnagiri", towns: ["Ratnagiri", "Chiplun", "Dapoli", "Khed"] },
      { district: "Sindhudurg", towns: ["Oros", "Sawantwadi", "Malvan", "Kudal", "Vengurla"] },
      { district: "Pune", towns: ["Pune", "Pimpri-Chinchwad", "Baramati", "Talegaon Dabhade", "Junnar", "Indapur"] },
      { district: "Satara", towns: ["Satara", "Karad", "Phaltan", "Wai", "Mahabaleshwar"] },
      { district: "Sangli", towns: ["Sangli", "Miraj", "Islampur", "Vita", "Tasgaon"] },
      { district: "Kolhapur", towns: ["Kolhapur", "Ichalkaranji", "Jaysingpur", "Gadhinglaj", "Kagal"] },
      { district: "Solapur", towns: ["Solapur", "Pandharpur", "Barshi", "Akluj", "Karmala"] },
      { district: "Ahilyanagar", towns: ["Ahilyanagar", "Shrirampur", "Sangamner", "Shirdi", "Kopargaon"] },
      { district: "Nashik", towns: ["Nashik", "Malegaon", "Manmad", "Igatpuri", "Sinnar", "Yeola"] },
      { district: "Dhule", towns: ["Dhule", "Shirpur", "Dondaicha", "Sakri"] },
      { district: "Nandurbar", towns: ["Nandurbar", "Shahada", "Taloda", "Navapur"] },
      { district: "Jalgaon", towns: ["Jalgaon", "Bhusawal", "Amalner", "Chalisgaon", "Faizpur"] },
      { district: "Chhatrapati Sambhajinagar", towns: ["Chhatrapati Sambhajinagar", "Paithan", "Vaijapur", "Sillod", "Kannad"] },
      { district: "Jalna", towns: ["Jalna", "Ambad", "Partur", "Bhokardan"] },
      { district: "Beed", towns: ["Beed", "Ambajogai", "Parli Vaijnath", "Georai", "Majalgaon"] },
      { district: "Dharashiv", towns: ["Dharashiv", "Tuljapur", "Naldurg", "Umarga", "Paranda"] },
      { district: "Latur", towns: ["Latur", "Udgir", "Ausa", "Nilanga", "Ahmadpur"] },
      { district: "Nanded", towns: ["Nanded", "Degloor", "Kinwat", "Biloli", "Mukhed"] },
      { district: "Parbhani", towns: ["Parbhani", "Gangakhed", "Pathri", "Jintur", "Selu"] },
      { district: "Hingoli", towns: ["Hingoli", "Basmath", "Kalamnuri", "Sengaon"] },
      { district: "Buldhana", towns: ["Buldhana", "Khamgaon", "Malkapur", "Shegaon", "Mehkar"] },
      { district: "Akola", towns: ["Akola", "Akot", "Murtizapur", "Balapur", "Telhara"] },
      { district: "Washim", towns: ["Washim", "Karanja", "Risod", "Mangrulpir"] },
      { district: "Amravati", towns: ["Amravati", "Achalpur", "Anjangaon Surji", "Paratwada", "Warud"] },
      { district: "Yavatmal", towns: ["Yavatmal", "Pusad", "Wani", "Digras", "Umarkhed"] },
      { district: "Wardha", towns: ["Wardha", "Hinganghat", "Pulgaon", "Arvi", "Deoli"] },
      { district: "Nagpur", towns: ["Nagpur", "Kamptee", "Katol", "Umred", "Saoner", "Hingna"] },
      { district: "Bhandara", towns: ["Bhandara", "Tumsar", "Pauni", "Sakoli"] },
      { district: "Gondia", towns: ["Gondia", "Tirora", "Amgaon", "Goregaon"] },
      { district: "Chandrapur", towns: ["Chandrapur", "Ballarpur", "Rajura", "Warora", "Bhadravati"] },
      { district: "Gadchiroli", towns: ["Gadchiroli", "Desaiganj", "Aheri", "Armori", "Kurkheda"] },
    ],
    faqs: [
      {
        q: "Is 103 the women's helpline everywhere in Maharashtra?",
        a: "No. Maharashtra Police publish 103 for the Mumbai, Thane and Navi Mumbai police units only, and 1091 for the rest of the state. Advice that gives 103 to a reader in Pune, Nashik or Nagpur is quoting a Mumbai-region number. Note also that 181 here is a women and child development department line, not a police one.",
      },
      {
        q: "Which cities in Maharashtra have a police commissioner, and does a rural force exist too?",
        a: "Eleven cities are listed as commissionerates: Mumbai, Thane, Navi Mumbai, Mira-Bhayandar and Vasai-Virar, Pune, Pimpri-Chinchwad, Nagpur, Nashik, Chhatrapati Sambhajinagar, Amravati and Solapur. Seven of them have a separate rural district with its own superintendent, namely Thane, Pune, Nagpur, Nashik, Chhatrapati Sambhajinagar, Amravati and Solapur. Navi Mumbai and Pimpri-Chinchwad have no rural unit of their own, so the land around them falls to Thane Rural and Pune Rural.",
      },
      {
        q: "Is 14407 a Nagpur number?",
        a: "No, although it is often quoted that way. It is the Maharashtra Cyber helpline and runs statewide, appearing on district police sites at the far end of the state. Use it alongside the national 1930 for cyber complaints.",
      },
      {
        q: "Do hotels in Maharashtra have to install cameras?",
        a: "There is no statewide requirement. The Mumbai order people cite was a sixty day city order that expired in March 2021. A district order reported in Raigad requires cameras at entry and exit points, reception, corridors and parking with thirty days of retention, and expressly says they must not be inside rooms or bathrooms, which is the useful line if an operator suggests otherwise.",
      },
      {
        q: "Are paying guest accommodation and hostels regulated in Maharashtra?",
        a: "Not at state level. We found no Maharashtra statute or statewide rules governing paying guest accommodation or private hostels. Licensing is municipal and varies between corporations, so what applies in Pune is not necessarily what applies in Nagpur.",
      },
    ],
  },
  {
    slug: "uttar-pradesh",
    state: "Uttar Pradesh",
    seoTitle: "Bug Sweeping Services in Uttar Pradesh | TSCM Sweeps",
    heroTitle: "Bug Sweeping Services in Uttar Pradesh",
    heroSubtitle:
      "TSCM bug sweeps across Uttar Pradesh, where a commissionerate covers the whole district and there is no rural force to fall back on.",
    metaDescription:
      "Bug sweeping services across Uttar Pradesh: TSCM sweeps district by district, with the state's seven commissionerates, e-FIR limits and Sarai Act registration explained.",
    intro:
      "Uttar Pradesh is the largest state in the country by population and one of the more centralised in how it polices its cities, which has a direct consequence for anyone reporting a covert recording device. The sweep itself is the same work everywhere: radio-frequency analysis, a non-linear junction detector for electronics that are switched off, optical and thermal checks, and a physical inspection. What this page sets out is what happens when you take the result of that to the police.",
    policing: {
      heading: "In Uttar Pradesh a commissionerate swallows the whole district",
      body: [
        "Seven cities in Uttar Pradesh are policed as commissionerates: Lucknow, Gautam Buddh Nagar, Kanpur Nagar, Varanasi, Agra, Ghaziabad and Prayagraj. Lucknow, Gautam Buddh Nagar and Kanpur Nagar came first in 2020 and 2021, Varanasi followed in 2021, and Agra, Ghaziabad and Prayagraj were added in November 2022.",
        "Here is the fact that makes Uttar Pradesh different from almost every other state, and it is the most useful line on this page. None of those seven has a separate rural superintendent. The commissioner covers the entire district. Lucknow's remaining rural stations were merged in November 2022, the eleven stations that made up Kanpur Outer were merged at the same time, Varanasi Rural followed later that month, and Agra, Ghaziabad and Prayagraj were notified for the whole district from the start, expressly including their rural stations. In most states a rural superintendent is a second door to knock on. In a Uttar Pradesh commissionerate district there is no second door.",
        "A check you can do yourself confirms it: the state's own official list of police units runs to exactly seventy five entries, seven commissionerates plus sixty eight districts, which is the same as the number of districts in the state. If any commissionerate had kept a rural district alongside it, there would be more than seventy five.",
        "One caution if you go looking. The Varanasi district website still shows a superintendent of police for rural Varanasi heading eleven rural stations. That page has not been updated since the 2022 merger and contradicts the state police's own current unit list. Note also that Uttar Pradesh has seventy five districts, not the seventy six that some sources dated 2025 report: the Maha Kumbh area of Prayagraj was notified as a temporary district by a district magistrate and it lapsed at the end of March 2025.",
        "Cyber coverage is one of the clearest in the country. There is a cyber police station in every one of the seventy five districts and commissionerates, up from eighteen at range level before a cabinet decision in December 2023 added fifty seven more. If you see the figures eighteen, fifty seven and seventy five quoted against each other, they are the old total, the number added and the current total. The wing is headquartered at police headquarters in Lucknow and the helpline is 1930.",
      ],
    },
    reporting: {
      heading: "You cannot file online if you know who did it",
      body: [
        "Uttar Pradesh's e-FIR facility states its own limit plainly on the portal: it is available only for cases with an unknown accused and for non special report categories. If you can name the person you suspect, the online route is closed to you and the complaint is made at the police station. That is a sharper restriction than in most states, and it is exactly the situation many people are in after a sweep, because a device found in a private space usually narrows the field of who could have placed it. The state publishes an e-FIR helpline on 0522 2390261, and the same service runs through the state police citizen app.",
        "On helplines, four numbers get confused with each other here. 1090, the Women Power Line, is run by Uttar Pradesh Police through their women and child security organisation and is based in Lucknow. 181 is a women's helpline run by the women welfare department, linked to the state's one stop centres, and it is not a police line; some district portals list it and others do not. 1076 is the Chief Minister's grievance helpline, for complaints about government departments. And the anti-corruption number published on Uttar Pradesh district portals is 1031, not the 1064 that circulates for other states. Emergencies go to 112 and cyber financial fraud to 1930.",
        "One practical note if you are searching for official pages: several Uttar Pradesh government sites are in poor technical health at the moment, including the certificate on the site that the police themselves link to for 1090. A broken link is not evidence that a service has stopped.",
      ],
    },
    accommodation: {
      heading: "Hotels and paying guest accommodation register under an 1867 Act, and cameras are only a form field",
      body: [
        "Accommodation in Uttar Pradesh is registered under section 3 of the Sarais Act of 1867, a central Act administered by the district magistrate rather than by the police. Registration forms published by district administrations make clear that the net is wide: guest houses, rest houses, hotels, lodges and, expressly, paying guest accommodation all fall inside it. There is no separate Uttar Pradesh statute for paying guest accommodation or private hostels; they are pulled in through this route.",
        "The detail worth carrying is what those forms do with cameras. On the district registration form we examined, cameras appear as one of six tick items under a security features heading, alongside boundary walls, fencing, gates, metal detectors and baggage scanning. It is a disclosure field: the operator states what exists. Nothing in it requires cameras to be installed, and we found no Uttar Pradesh government order that does. So if a hotel or hostel tells you cameras are mandatory here, or that registration proves anything about them, neither is accurate.",
        "Two things get misquoted as hotel camera rules and are neither. A 2024 state directive about displaying owner names, police verification of staff and installing cameras applied to food establishments, not to lodging. And the state's bed and breakfast and homestay policy of 2025 is real, but the claim that it mandates cameras appears only on aggregator sites and we could not verify it in the policy itself, which is published as a scanned document.",
        "We found no advisory from Uttar Pradesh Police specifically about hidden or spy cameras. Their cyber advisories cover financial fraud, social media harassment, identity theft, phishing and crimes against women and children, with nothing on covert recording devices.",
      ],
    },
    cityPages: ["noida", "lucknow", "kanpur"],
    districts: [
      { district: "Lucknow", towns: ["Lucknow", "Malihabad", "Bakshi Ka Talab"] },
      { district: "Gautam Buddh Nagar", towns: ["Noida", "Greater Noida", "Dadri", "Jewar", "Dankaur"] },
      { district: "Ghaziabad", towns: ["Ghaziabad", "Modinagar", "Loni", "Muradnagar"] },
      { district: "Hapur", towns: ["Hapur", "Garhmukteshwar", "Pilkhuwa"] },
      { district: "Meerut", towns: ["Meerut", "Mawana", "Sardhana", "Kithaur"] },
      { district: "Baghpat", towns: ["Baghpat", "Baraut", "Khekada"] },
      { district: "Muzaffarnagar", towns: ["Muzaffarnagar", "Khatauli", "Budhana"] },
      { district: "Shamli", towns: ["Shamli", "Kairana", "Kandhla"] },
      { district: "Saharanpur", towns: ["Saharanpur", "Deoband", "Gangoh", "Nakur"] },
      { district: "Bijnor", towns: ["Bijnor", "Najibabad", "Nagina", "Dhampur"] },
      { district: "Amroha", towns: ["Amroha", "Hasanpur", "Gajraula"] },
      { district: "Moradabad", towns: ["Moradabad", "Thakurdwara", "Kanth"] },
      { district: "Sambhal", towns: ["Bahjoi", "Sambhal", "Chandausi"] },
      { district: "Rampur", towns: ["Rampur", "Bilaspur", "Tanda", "Suar"] },
      { district: "Bareilly", towns: ["Bareilly", "Aonla", "Faridpur", "Nawabganj"] },
      { district: "Pilibhit", towns: ["Pilibhit", "Bisalpur", "Puranpur"] },
      { district: "Shahjahanpur", towns: ["Shahjahanpur", "Tilhar", "Puwayan"] },
      { district: "Budaun", towns: ["Budaun", "Bisauli", "Sahaswan", "Ujhani"] },
      { district: "Bulandshahr", towns: ["Bulandshahr", "Khurja", "Sikandrabad", "Anupshahr"] },
      { district: "Aligarh", towns: ["Aligarh", "Khair", "Atrauli", "Iglas"] },
      { district: "Hathras", towns: ["Hathras", "Sikandra Rao", "Sadabad"] },
      { district: "Kasganj", towns: ["Kasganj", "Soron", "Patiyali"] },
      { district: "Etah", towns: ["Etah", "Jalesar", "Marehra"] },
      { district: "Mathura", towns: ["Mathura", "Vrindavan", "Kosi Kalan", "Govardhan"] },
      { district: "Agra", towns: ["Agra", "Fatehpur Sikri", "Etmadpur", "Bah"] },
      { district: "Firozabad", towns: ["Firozabad", "Shikohabad", "Tundla"] },
      { district: "Mainpuri", towns: ["Mainpuri", "Bhogaon", "Karhal"] },
      { district: "Etawah", towns: ["Etawah", "Bharthana", "Jaswantnagar"] },
      { district: "Auraiya", towns: ["Auraiya", "Dibiyapur", "Bidhuna"] },
      { district: "Farrukhabad", towns: ["Fatehgarh", "Farrukhabad", "Kaimganj"] },
      { district: "Kannauj", towns: ["Kannauj", "Chhibramau", "Tirwa"] },
      { district: "Kanpur Nagar", towns: ["Kanpur", "Bithoor", "Ghatampur"] },
      { district: "Kanpur Dehat", towns: ["Akbarpur (Mati)", "Rura", "Pukhrayan"] },
      { district: "Unnao", towns: ["Unnao", "Bangarmau", "Safipur"] },
      { district: "Hardoi", towns: ["Hardoi", "Shahabad", "Sandila"] },
      { district: "Sitapur", towns: ["Sitapur", "Laharpur", "Biswan"] },
      { district: "Lakhimpur Kheri", towns: ["Lakhimpur", "Gola Gokarannath", "Palia Kalan"] },
      { district: "Barabanki", towns: ["Barabanki", "Nawabganj", "Zaidpur"] },
      { district: "Rae Bareli", towns: ["Rae Bareli", "Lalganj", "Unchahar"] },
      { district: "Amethi", towns: ["Gauriganj", "Amethi", "Musafirkhana"] },
      { district: "Sultanpur", towns: ["Sultanpur", "Lambhua", "Kadipur"] },
      { district: "Pratapgarh", towns: ["Pratapgarh", "Kunda", "Lalganj"] },
      { district: "Prayagraj", towns: ["Prayagraj", "Phulpur", "Handia"] },
      { district: "Kaushambi", towns: ["Manjhanpur", "Bharwari", "Sirathu"] },
      { district: "Fatehpur", towns: ["Fatehpur", "Bindki", "Khaga"] },
      { district: "Banda", towns: ["Banda", "Atarra", "Naraini"] },
      { district: "Chitrakoot", towns: ["Chitrakoot Dham", "Rajapur", "Mau"] },
      { district: "Hamirpur", towns: ["Hamirpur", "Rath", "Maudaha"] },
      { district: "Mahoba", towns: ["Mahoba", "Charkhari", "Kulpahar"] },
      { district: "Jhansi", towns: ["Jhansi", "Mauranipur", "Chirgaon"] },
      { district: "Lalitpur", towns: ["Lalitpur", "Mehroni", "Talbehat"] },
      { district: "Jalaun", towns: ["Orai", "Jalaun", "Konch"] },
      { district: "Varanasi", towns: ["Varanasi", "Ramnagar", "Pindra"] },
      { district: "Chandauli", towns: ["Chandauli", "Mughalsarai", "Chakia"] },
      { district: "Ghazipur", towns: ["Ghazipur", "Jamania", "Saidpur"] },
      { district: "Ballia", towns: ["Ballia", "Rasra", "Bansdih"] },
      { district: "Mau", towns: ["Mau", "Ghosi", "Madhuban"] },
      { district: "Azamgarh", towns: ["Azamgarh", "Mubarakpur", "Phulpur"] },
      { district: "Jaunpur", towns: ["Jaunpur", "Shahganj", "Mariahu"] },
      { district: "Bhadohi", towns: ["Gyanpur", "Bhadohi", "Gopiganj"] },
      { district: "Mirzapur", towns: ["Mirzapur", "Chunar", "Ahraura"] },
      { district: "Sonbhadra", towns: ["Robertsganj", "Renukoot", "Obra"] },
      { district: "Gorakhpur", towns: ["Gorakhpur", "Sahjanwa", "Chauri Chaura"] },
      { district: "Maharajganj", towns: ["Maharajganj", "Nautanwa", "Siswa Bazar"] },
      { district: "Kushinagar", towns: ["Padrauna", "Kasia", "Hata"] },
      { district: "Deoria", towns: ["Deoria", "Barhaj", "Salempur"] },
      { district: "Basti", towns: ["Basti", "Harraiya", "Rudhauli"] },
      { district: "Sant Kabir Nagar", towns: ["Khalilabad", "Mehdawal", "Dhanghata"] },
      { district: "Siddharthnagar", towns: ["Naugarh", "Siddharthnagar", "Bansi", "Domariyaganj"] },
      { district: "Ayodhya", towns: ["Ayodhya", "Faizabad", "Rudauli"] },
      { district: "Ambedkar Nagar", towns: ["Akbarpur", "Tanda", "Jalalpur"] },
      { district: "Gonda", towns: ["Gonda", "Colonelganj", "Nawabganj"] },
      { district: "Balrampur", towns: ["Balrampur", "Tulsipur", "Utraula"] },
      { district: "Shravasti", towns: ["Bhinga", "Ikauna"] },
      { district: "Bahraich", towns: ["Bahraich", "Nanpara", "Rupaidiha"] },
    ],
    faqs: [
      {
        q: "Is there a rural police force in Uttar Pradesh commissionerate districts?",
        a: "No. This is what makes Uttar Pradesh different. All seven commissionerates, namely Lucknow, Gautam Buddh Nagar, Kanpur Nagar, Varanasi, Agra, Ghaziabad and Prayagraj, cover their entire district, with the rural stations merged in by the end of 2022. There is no separate rural superintendent to approach. The Varanasi district website still shows one, but that page is out of date.",
      },
      {
        q: "Can I file an e-FIR in Uttar Pradesh for a hidden camera?",
        a: "Only if you cannot name a suspect. The portal states that the e-FIR facility is available only for unknown accused and non special report cases. Since a device found in a private space usually narrows who could have placed it, most people in this situation will be making the complaint at the police station. The state publishes an e-FIR helpline on 0522 2390261.",
      },
      {
        q: "What is the difference between 1090, 181 and 1076 in Uttar Pradesh?",
        a: "1090 is the Women Power Line, run by Uttar Pradesh Police from Lucknow. 181 is a women's helpline run by the women welfare department, not the police, and some district portals list it while others do not. 1076 is the Chief Minister's grievance helpline for complaints about government departments. Use 112 for emergencies and 1930 for cyber crime.",
      },
      {
        q: "Do hotels or paying guest accommodation in Uttar Pradesh have to install cameras?",
        a: "No. They register with the district magistrate under section 3 of the Sarais Act 1867, and paying guest accommodation is expressly within that net. On the district registration form cameras are one of six security tick boxes, a disclosure of what exists rather than a requirement to install anything. We found no Uttar Pradesh order making cameras compulsory in lodging.",
      },
      {
        q: "How many districts does Uttar Pradesh have?",
        a: "Seventy five. Sources dated 2025 that say seventy six are counting the Maha Kumbh area of Prayagraj, which a district magistrate notified as a temporary district and which lapsed at the end of March 2025. Every one of the seventy five has its own cyber police station.",
      },
    ],
  },
  {
    slug: "madhya-pradesh",
    state: "Madhya Pradesh",
    seoTitle: "Bug Sweeping Services in Madhya Pradesh | TSCM Sweeps",
    heroTitle: "Bug Sweeping Services in Madhya Pradesh",
    heroSubtitle:
      "TSCM bug sweeps across Madhya Pradesh, where only two cities have a commissioner and 181 is not a police number.",
    metaDescription:
      "Bug sweeping services across Madhya Pradesh: TSCM sweeps district by district, with the state's two commissionerates, e-FIR limits and helpline differences explained.",
    intro:
      "Madhya Pradesh is the second largest state in the country by area, and outside two cities it is policed entirely through district superintendents. That shapes what happens after a sweep more than anything else about the state. The work itself is unchanged: radio-frequency analysis for anything transmitting, a non-linear junction detector for electronics left switched off, optical and thermal checks, and a hands-on inspection of fittings, voids and furniture.",
    policing: {
      heading: "Two commissionerates, and both cover their whole district",
      body: [
        "Only Bhopal and Indore are policed as commissionerates in Madhya Pradesh, both since December 2021. Jabalpur, Gwalior and Ujjain have been proposed over the years and none has been added as at September 2026, so everywhere outside those two cities your complaint goes to a district superintendent.",
        "Where those two differ from most commissionerate cities elsewhere is that neither leaves a rural force behind. The published jurisdiction of each covers the whole district, villages included: Bhopal's commissionerate accounts for the district's six hundred and fourteen villages and Indore's for its six hundred and seventy six. So unlike Maharashtra, where seven cities have a separate rural superintendent you might need instead, in Madhya Pradesh there is no rural counterpart to fall back on in either city.",
        "One naming point that trips people up in legal writing: there is no Madhya Pradesh Police Act. The force operates under the central Police Act of 1861, so anyone citing a state police statute at you is mistaken.",
        "The state has fifty five districts, the most recent additions being Mauganj, Maihar and Pandhurna in 2023. Treat that number as current rather than permanent: a state reorganisation commission appointed in 2024 is reviewing district, tehsil and block boundaries, and the exercise is still running. Nagda has been announced as a district more than once and has never actually been notified.",
        "Cyber matters run through the State Cyber Police headquarters in Bhopal, with a cyber cell under the superintendent in each district. Sources disagree on how many cyber police stations exist and the state publishes no list, so we give no number. One practical warning: the state's own cyber crime subdomain no longer resolves, so if a link fails, use the national cyber crime portal or 1930 rather than assuming the service has closed.",
      ],
    },
    reporting: {
      heading: "181 is not a police number here, and the e-FIR lapses in three days",
      body: [
        "This is the correction that matters most in Madhya Pradesh, because it is the reverse of several neighbouring states. The women's helpline published by Madhya Pradesh Police is 1090. The 181 number, which is a women's line in Maharashtra and elsewhere, is the Chief Minister's helpline here, a grievance service for complaints about government departments, running set hours rather than around the clock. Dialling it in an emergency wastes time you do not have. For emergencies both 112 and 100 are answered, since the state moved to 112 while continuing to carry 100 on its own helpline page. Cyber financial fraud goes to 1930 and children to 1098.",
        "On the e-FIR, the state police describe it as an optional facility rather than a registered FIR. Its categories are broader than most write-ups suggest, because those describe the scope at launch: the live portal lists theft, vehicle theft, online financial fraud, and crimes against women and children. What has not changed is the ending. You are expected at the police station within about three days, and the portal states plainly that the e-FIR is rejected if you do not appear. Treat it as a way of starting a record rather than a way of avoiding the station, and keep the sweep documentation for the visit itself.",
      ],
    },
    accommodation: {
      heading: "No statewide camera rule, and the guest record duty runs two months at a time",
      body: [
        "Madhya Pradesh has no statewide requirement for cameras in hotels, lodges, paying guest accommodation or hostels. We looked for a statute, a statutory rule, a gazette notification and a police headquarters standing order, and found none of them. The state's homestay and bed and breakfast schemes are voluntary tourism registrations and their official pages carry no camera requirement, despite aggregator sites claiming otherwise.",
        "What does exist, and what you can actually hold an operator to, works differently from most states. The enforceable duty comes from city prohibitory orders made by the police commissioners in Bhopal and Indore, requiring hotels, lodges, dharamshalas, resorts, guest houses and hostels to keep full guest records and share them with the local police station, and requiring landlords to report tenants and paying guests within set periods. Breach is a punishable offence, and Indore filed cases against establishments in a drive in November 2025. The catch is that these orders run for about two months at a time and are reissued, so there is always a current one and it is worth asking which. Neither order requires cameras.",
        "The state police citizen portal also runs a tenant and paying guest information service, through which landlords submit occupant details to the local police station online. That is an administrative service rather than a statutory duty, but it means the record you might want to ask about often exists.",
        "We found no advisory from Madhya Pradesh Police specifically about hidden or spy cameras. Their cyber security pages cover stalking, card cloning, fake job offers and account security, with nothing on covert recording devices.",
      ],
    },
    cityPages: ["indore", "bhopal"],
    districts: [
      { district: "Bhopal", towns: ["Bhopal", "Berasia"] },
      { district: "Indore", towns: ["Indore", "Mhow", "Sanwer", "Depalpur"] },
      { district: "Jabalpur", towns: ["Jabalpur", "Sihora", "Panagar"] },
      { district: "Gwalior", towns: ["Gwalior", "Dabra", "Bhitarwar"] },
      { district: "Ujjain", towns: ["Ujjain", "Nagda", "Khachrod", "Mahidpur"] },
      { district: "Sagar", towns: ["Sagar", "Bina", "Makronia", "Khurai"] },
      { district: "Rewa", towns: ["Rewa", "Mangawan", "Gurh"] },
      { district: "Satna", towns: ["Satna", "Nagod", "Unchahara"] },
      { district: "Maihar", towns: ["Maihar", "Amarpatan"] },
      { district: "Mauganj", towns: ["Mauganj", "Hanumana"] },
      { district: "Chhindwara", towns: ["Chhindwara", "Parasia", "Amarwara"] },
      { district: "Pandhurna", towns: ["Pandhurna", "Sausar"] },
      { district: "Dhar", towns: ["Dhar", "Pithampur", "Dhamnod", "Manawar"] },
      { district: "Khargone", towns: ["Khargone", "Sanawad", "Barwaha", "Maheshwar"] },
      { district: "Khandwa", towns: ["Khandwa", "Mundi", "Pandhana"] },
      { district: "Burhanpur", towns: ["Burhanpur", "Nepanagar"] },
      { district: "Barwani", towns: ["Barwani", "Sendhwa", "Rajpur"] },
      { district: "Alirajpur", towns: ["Alirajpur", "Jobat", "Bhabra"] },
      { district: "Jhabua", towns: ["Jhabua", "Thandla", "Petlawad"] },
      { district: "Ratlam", towns: ["Ratlam", "Jaora", "Sailana", "Alot"] },
      { district: "Mandsaur", towns: ["Mandsaur", "Neemuch road", "Sitamau", "Garoth"] },
      { district: "Neemuch", towns: ["Neemuch", "Manasa", "Jawad"] },
      { district: "Dewas", towns: ["Dewas", "Sonkatch", "Kannod", "Bagli"] },
      { district: "Shajapur", towns: ["Shajapur", "Shujalpur", "Akodia"] },
      { district: "Agar Malwa", towns: ["Agar", "Susner", "Nalkheda"] },
      { district: "Rajgarh", towns: ["Rajgarh", "Biaora", "Narsinghgarh", "Khilchipur"] },
      { district: "Sehore", towns: ["Sehore", "Ashta", "Ichhawar", "Budni"] },
      { district: "Raisen", towns: ["Raisen", "Mandideep", "Begamganj", "Silwani"] },
      { district: "Vidisha", towns: ["Vidisha", "Ganj Basoda", "Sironj", "Kurwai"] },
      { district: "Narmadapuram", towns: ["Narmadapuram", "Itarsi", "Pipariya", "Sohagpur"] },
      { district: "Harda", towns: ["Harda", "Timarni", "Khirkiya"] },
      { district: "Betul", towns: ["Betul", "Multai", "Amla", "Sarni"] },
      { district: "Seoni", towns: ["Seoni", "Lakhnadon", "Keolari"] },
      { district: "Balaghat", towns: ["Balaghat", "Waraseoni", "Malajkhand", "Katangi"] },
      { district: "Mandla", towns: ["Mandla", "Nainpur", "Bichhiya"] },
      { district: "Dindori", towns: ["Dindori", "Shahpura"] },
      { district: "Narsinghpur", towns: ["Narsinghpur", "Gadarwara", "Kareli"] },
      { district: "Katni", towns: ["Katni", "Vijayraghavgarh", "Barhi"] },
      { district: "Umaria", towns: ["Umaria", "Nowrozabad", "Bandhavgarh"] },
      { district: "Shahdol", towns: ["Shahdol", "Burhar", "Jaisinghnagar"] },
      { district: "Anuppur", towns: ["Anuppur", "Kotma", "Amarkantak", "Bijuri"] },
      { district: "Singrauli", towns: ["Singrauli", "Waidhan", "Deosar"] },
      { district: "Sidhi", towns: ["Sidhi", "Churhat", "Majhauli"] },
      { district: "Panna", towns: ["Panna", "Pawai", "Ajaygarh"] },
      { district: "Damoh", towns: ["Damoh", "Hatta", "Patharia"] },
      { district: "Chhatarpur", towns: ["Chhatarpur", "Khajuraho", "Nowgong", "Harpalpur"] },
      { district: "Tikamgarh", towns: ["Tikamgarh", "Jatara", "Baldeogarh"] },
      { district: "Niwari", towns: ["Niwari", "Orchha", "Prithvipur"] },
      { district: "Datia", towns: ["Datia", "Seondha", "Bhander"] },
      { district: "Shivpuri", towns: ["Shivpuri", "Kolaras", "Karera", "Pichhore"] },
      { district: "Guna", towns: ["Guna", "Raghogarh", "Chachaura"] },
      { district: "Ashoknagar", towns: ["Ashoknagar", "Chanderi", "Mungaoli"] },
      { district: "Bhind", towns: ["Bhind", "Gohad", "Lahar", "Mehgaon"] },
      { district: "Morena", towns: ["Morena", "Ambah", "Porsa", "Sabalgarh"] },
      { district: "Sheopur", towns: ["Sheopur", "Vijaypur", "Karahal"] },
    ],
    faqs: [
      {
        q: "Is 181 the women's helpline in Madhya Pradesh?",
        a: "No, and this is the most common mistake here. In Madhya Pradesh 181 is the Chief Minister's helpline, a grievance service for complaints about government departments, running set hours rather than around the clock. The women's helpline published by Madhya Pradesh Police is 1090. Use 112 or 100 for emergencies and 1930 for cyber financial fraud.",
      },
      {
        q: "Which cities in Madhya Pradesh have a police commissioner?",
        a: "Only Bhopal and Indore, both since December 2021. Jabalpur, Gwalior and Ujjain have been proposed but none has been added as at September 2026. Both commissionerates cover their whole district including its villages, so unlike some states there is no separate rural superintendent to approach instead.",
      },
      {
        q: "Can I file an e-FIR in Madhya Pradesh instead of going to the police station?",
        a: "You can start one, but it will not spare you the visit. Madhya Pradesh Police call it an optional facility rather than a registered FIR, and the portal states that it is rejected if you do not attend the police station within about three days. Its categories are broader than the vehicle theft framing older write-ups repeat, now covering theft, online financial fraud and crimes against women and children.",
      },
      {
        q: "Do hotels or hostels in Madhya Pradesh have to install cameras?",
        a: "No. There is no statewide camera requirement for hotels, lodges, paying guest accommodation or hostels. What exists, in Bhopal and Indore only, are police commissioner orders requiring guest and tenant records to be kept and shared with the local police station. Breach is punishable and cases were filed in Indore in November 2025. Those orders run about two months at a time and are reissued.",
      },
      {
        q: "Does Madhya Pradesh have its own police Act?",
        a: "No. The force operates under the central Police Act of 1861; there is no Madhya Pradesh Police Act, so anyone citing one is mistaken. That matters mainly when someone claims a state law requires something of a hotel or hostel.",
      },
    ],
  },
];

